name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint and save report
      run: |
        pylint --exit-zero $(git ls-files '*.py') > pylint-report.txt

    - name: Upload pylint report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report-${{ matrix.python-version }}
        path: pylint-report.txt
